language: objective-c

env:
  global:
    - EnableNuGetPackageRestore=true
  matrix:
    - MONO_VERSION="3.2.5"

# whitelist
branches:
  only:
    - master

before_install:
  - wget "http://download.xamarin.com/MonoFrameworkMDK/Macx86/MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg"
  - sudo installer -pkg "MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg" -target /

install:
  - mono .nuget/NuGet.exe install FSharp.Formatting -Version 2.2.11-beta -OutputDirectory packages
  - mono .nuget/NuGet.exe install Microsoft.AspNet.Razor -Version 2.0.30506.0 -OutputDirectory packages
  - mono .nuget/NuGet.exe install RazorEngine -Version 3.3.0 -OutputDirectory pacages

before_script:
 - chmod +x build.sh

script: 
  - ./build.sh All
