language: objective-c

env:
  global:
    - EnableNuGetPackageRestore=true
  matrix:
    - MONO_VERSION="3.2.5"

before_install:
  - wget "http://download.xamarin.com/MonoFrameworkMDK/Macx86/MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg"
  - sudo installer -pkg "MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg" -target /


install:
  - mono .nuget/NuGet.exe install NUnit.Runners -Version 2.6.3 -OutputDirectory packages -ExcludeVersion

script: 
  - xbuild Arcadia.sln /p:Configuration=Release
