language: objective-c

env:
  global:
    - EnableNuGetPackageRestore=true
  matrix:
    - MONO_VERSION="3.2.5"

# whitelist
branches:
  only:
    - master

before_install:
  - wget "http://download.xamarin.com/MonoFrameworkMDK/Macx86/MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg"
  - sudo installer -pkg "MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg" -target /

install:
  - mono .nuget/NuGet.exe install NUnit.Runners -Version 2.6.3 -OutputDirectory packages -ExcludeVersion

# only build core Arcadia and tests since mono does not support WPF libs
script: 
  - xbuild src/Arcadia/Arcadia.fsproj /p:Configuration=Release
  - xbuild tests/Arcadia.Tests/Arcadia.Tests.fsproj /p:Configuration=Release
  - mono --runtime=v4.0 packages/NUnit.Runners/tools/nunit-console.exe tests/Arcadia.Tests/bin/Release/Arcadia.Tests.dll
